# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


name: talk2vino-nginx
replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.22-alpine"

service:
  type: ClusterIP
  port: 80
